// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type ShortUrl struct {
	ID          int64     `json:"id"`
	ShortPath   string    `json:"short_path"`
	OriginalUrl string    `json:"original_url"`
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type TelegramAuthToken struct {
	Token          string    `json:"token"`
	TelegramChatID int64     `json:"telegram_chat_id"`
	ExpiresAt      time.Time `json:"expires_at"`
}

type UrlClick struct {
	ID          int64          `json:"id"`
	ShortUrlID  int64          `json:"short_url_id"`
	ClickedAt   time.Time      `json:"clicked_at"`
	CountryCode sql.NullString `json:"country_code"`
	UserAgent   sql.NullString `json:"user_agent"`
}

type User struct {
	ID             int64         `json:"id"`
	Username       string        `json:"username"`
	PasswordHash   string        `json:"password_hash"`
	Role           string        `json:"role"`
	TelegramChatID sql.NullInt64 `json:"telegram_chat_id"`
	CreatedAt      time.Time     `json:"created_at"`
}
