// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type ShortUrl struct {
	ID          int64     `json:"id"`
	ShortPath   string    `json:"short_path"`
	OriginalURL string    `json:"original_url"`
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type TelegramAuthToken struct {
	Token          string    `json:"token"`
	TelegramChatID int64     `json:"telegram_chat_id"`
	ExpiresAt      time.Time `json:"expires_at"`
}

type UrlClick struct {
	ID           int64          `json:"id"`
	ShortURLID   int64          `json:"short_url_id"`
	ClickedAt    time.Time      `json:"clicked_at"`
	CountryCode  sql.NullString `json:"country_code"`
	OSName       sql.NullString `json:"os_name"`
	BrowserName  sql.NullString `json:"browser_name"`
	RawUserAgent sql.NullString `json:"raw_user_agent"`
	IPAddress    sql.NullString `json:"ip_address"`
}

type User struct {
	ID             int64         `json:"id"`
	Username       string        `json:"username"`
	PasswordHash   string        `json:"password_hash"`
	Permissions    int64         `json:"permissions"`
	TelegramChatID sql.NullInt64 `json:"telegram_chat_id"`
	CreatedAt      time.Time     `json:"created_at"`
}
