// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	AggregateClicksByBrowser(ctx context.Context, shortUrlID int64) ([]AggregateClicksByBrowserRow, error)
	AggregateClicksByCountry(ctx context.Context, shortUrlID int64) ([]AggregateClicksByCountryRow, error)
	AggregateClicksByOS(ctx context.Context, shortUrlID int64) ([]AggregateClicksByOSRow, error)
	AggregateClicksByTimeRange(ctx context.Context, shortUrlID int64) ([]AggregateClicksByTimeRangeRow, error)
	CountClicksByShortURL(ctx context.Context, shortUrlID int64) (int64, error)
	CreateShortURL(ctx context.Context, arg CreateShortURLParams) (int64, error)
	CreateTelegramAuthToken(ctx context.Context, arg CreateTelegramAuthTokenParams) (string, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	DeleteShortURL(ctx context.Context, id int64) error
	DeleteTelegramAuthToken(ctx context.Context, token string) error
	GetShortURLByPath(ctx context.Context, shortPath string) (ShortUrl, error)
	GetTelegramAuthToken(ctx context.Context, token string) (TelegramAuthToken, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertClick(ctx context.Context, arg InsertClickParams) (int64, error)
	ListShortURLsByUser(ctx context.Context, userID int64) ([]ShortUrl, error)
	UpdateUserPermissions(ctx context.Context, arg UpdateUserPermissionsParams) error
	UpdateUserTelegramID(ctx context.Context, arg UpdateUserTelegramIDParams) error
}

var _ Querier = (*Queries)(nil)
